# Generated by Django 3.2.7 on 2021-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("batch", models.IntegerField()),
                ("post", models.CharField(default=None, max_length=50)),
                ("github_id", models.URLField(blank=True, max_length=100, null=True)),
                ("linkedin_id", models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
