# Generated by Django 3.2.7 on 2021-10-05 10:25

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("batch", models.PositiveIntegerField(blank=True, null=True)),
                ("dual_degree", models.BooleanField(default=False)),
                ("company", models.CharField(default=None, max_length=100)),
                (
                    "github_id",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_github_url],
                    ),
                ),
                (
                    "linkedin_id",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_linkedin_url],
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.alumni_upload
                    ),
                ),
                (
                    "profile_pic_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=50)),
                ("body", models.JSONField()),
                ("published", models.DateField(auto_now_add=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.blog_upload
                    ),
                ),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(default=None, max_length=50)),
                ("sub_event", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.gallery_upload
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(default=None, max_length=50)),
                ("name", models.CharField(default=None, max_length=50)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "github_link",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_github_url],
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.project_upload
                    ),
                ),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Volunteer", "Volunteer"),
                            ("Executive", "Executive"),
                            ("Coordinator", "Coordinator"),
                            ("President", "President"),
                            ("Vice President", " Vice President"),
                            ("Technical Lead", "Technical Lead"),
                            ("Finance Head", "Finance Head"),
                            ("Web Development Head", "Web Development Head"),
                            ("Public Relation Head", "Public Relation Head"),
                        ],
                        default="Volunteer",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "github_id",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_github_url],
                    ),
                ),
                (
                    "linkedin_id",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_linkedin_url],
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.team_upload
                    ),
                ),
                (
                    "profile_pic_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("event_date", models.DateTimeField()),
                ("venue", models.CharField(max_length=100)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.workshop_upload
                    ),
                ),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
