# Generated by Django 3.2.7 on 2021-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumni",
            name="title",
        ),
        migrations.RemoveField(
            model_name="teammodel",
            name="year",
        ),
        migrations.AddField(
            model_name="alumni",
            name="company",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="alumni",
            name="dual_degree",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alumni",
            name="image",
            field=models.URLField(
                default="http://uilove.in/realestate/listo/preview/img/profile-placeholder.jpg"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.URLField(
                default="https://assets.thehansindia.com/h-upload/2021/07/31/1092805-tech.webp"
            ),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="image",
            field=models.URLField(
                default="http://uilove.in/realestate/listo/preview/img/profile-placeholder.jpg"
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="image",
            field=models.URLField(
                default="https://s3.amazonaws.com/thumbnails.venngage.com/template/93542d3a-62a9-4674-a7ed-cb6852d160a3.png",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="title",
            field=models.CharField(
                choices=[
                    ("Volunteer", "Volunteer"),
                    ("Executive", "Executive"),
                    ("Coordinator", "Coordinator"),
                    ("President", "President"),
                    ("Vice President", " Vice President"),
                    ("Technical Lead", "Technical Lead"),
                    ("Finance Head", "Finance Head"),
                    ("Web Development Head", "Web Development Head"),
                    ("Public Relation Head", "Public Relation Head"),
                ],
                default="Volunteer",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
