# Generated by Django 3.2.7 on 2021-10-19 14:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumni",
            options={"verbose_name_plural": "Alumni"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name_plural": "Gallery"},
        ),
        migrations.AlterModelOptions(
            name="teammodel",
            options={"verbose_name_plural": "Team Members"},
        ),
        migrations.AddField(
            model_name="gallery",
            name="thumb_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.thumbnail_upload
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="thumb_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
