# Generated by Django 3.2.7 on 2021-09-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "teammodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.teammodel",
                    ),
                ),
            ],
            bases=("api.teammodel",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=50)),
                ("body", models.JSONField()),
                ("published", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("event_date", models.DateTimeField()),
                ("venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="teammodel",
            old_name="post",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="teammodel",
            old_name="batch",
            new_name="year",
        ),
    ]
