# Generated by Django 4.0 on 2022-10-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memberregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='acknowledgement',
            field=models.BooleanField(default=False, verbose_name='I agree and understand the procedures of the team interviews and a thorough line of questioning. I will hold no one accountable except for myself if I fail to adhere to the rules and regulations or fail to maintain discipline during the course of the interview. I will not hold the team and any of its members accountable for any untoward happening if selected.'),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='branch',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Material Science and Engineering', 'Material Science and Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Other', 'Other')], default='Electronics and Communication Engineering', max_length=60),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=100),
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe'), ('Not RSVPed Yet', 'Not RSVPed Yet')], default='Pending', max_length=50)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.workshop')),
            ],
            options={
                'verbose_name_plural': 'Attendees',
                'unique_together': {('email', 'workshop')},
            },
        ),
    ]
