# Generated by Django 3.2.7 on 2021-09-27 18:07

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210927_1157"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumni",
            name="image",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.RemoveField(
            model_name="teammodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="workshop",
            name="image",
        ),
        migrations.AddField(
            model_name="alumni",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.alumni_upload
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.blog_upload
            ),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.team_upload
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.workshop_upload
            ),
        ),
    ]
