# Generated by Django 3.2.7 on 2021-10-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20211019_2008"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
