# Generated by Django 3.2.7 on 2021-09-29 05:48

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210927_1807"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(default=None, max_length=50)),
                ("date", models.DateField()),
                ("sub_event", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.gallery_upload
                    ),
                ),
            ],
        ),
    ]
