# Generated by Django 4.0 on 2022-10-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_memberregistration_acknowledgement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='status',
        ),
    ]
