# Generated by Django 3.2.7 on 2021-09-30 11:06

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="github_id",
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                validators=[api.models.validate_github_url],
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="linkedin_id",
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                validators=[api.models.validate_linkedin_url],
            ),
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="github_id",
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                validators=[api.models.validate_github_url],
            ),
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="linkedin_id",
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                validators=[api.models.validate_linkedin_url],
            ),
        ),
    ]
