# Generated by Django 3.2.7 on 2021-10-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210930_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="profile_pic_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="cover_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="profile_pic_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="cover_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
