# Generated by Django 3.2.7 on 2021-10-04 09:52

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20211004_1105"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("description", models.CharField(max_length=2000)),
                ("year", models.DateField()),
                (
                    "github_link",
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[api.models.validate_github_url],
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.project_upload
                    ),
                ),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
