# Generated by Django 3.2.7 on 2021-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumni",
            name="year",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="date",
        ),
        migrations.AddField(
            model_name="alumni",
            name="batch",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="domain",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="description",
            field=models.TextField(),
        ),
    ]
